version: 2
references:
  ## Gradle Cache
  gradle_cache_key: &gradle_cache_key
    key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
  gradle_cache_path: &gradle_cache_path
    paths:
      - ~/.gradle
  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      <<: *gradle_cache_key
  save_gradle_cache: &save_gradle_cache
    save_cache:
      <<: *gradle_cache_key
      <<: *gradle_cache_path

jobs:
  build: # This is our first job.
    docker:
      - image: circleci/android:api-30
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - run: chmod 777 gradlew
      - *restore_gradle_cache
      - run: ./gradlew androidDependencies
      - *save_gradle_cache
      - run: ./gradlew build
workflows:
  version: 2
  build:
    jobs: # and here we list the jobs we are going to run.
      - build
